# Generated by Django 4.2.14 on 2024-11-05 15:28

import app_siad.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('comprovante_matricula', models.FileField(upload_to='comprovantes_matricula/')),
            ],
        ),
        migrations.CreateModel(
            name='EdicaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicao', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_fim_inscricao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateField()),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RepresentanteEsportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representacao', models.CharField(max_length=150, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('documento', models.FileField(upload_to='comprovantes_matricula/')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dados_escola', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_atletas', models.PositiveIntegerField()),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('regras_modalidade', models.TextField()),
                ('local', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Fem.', 'Feminino'), ('Geral', 'Geral'), ('Masc.', 'Masculino')], default='', max_length=5)),
                ('edicao_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.edicaoevento')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao_grupo', models.TextField()),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('edicao_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='app_siad.edicaoevento')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='representante_esportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.representanteesportivo'),
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=app_siad.models.get_upload_to)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.edicaoevento')),
            ],
        ),
        migrations.AddField(
            model_name='edicaoevento',
            name='evento_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.eventooriginal'),
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAtleta', models.PositiveIntegerField(default=1)),
                ('maxAtleta', models.PositiveIntegerField(default=1)),
                ('tipo_divisao', models.CharField(choices=[('G', 'Grupo'), ('I', 'Individual')], default='', max_length=1)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='AtletaGrupoDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.atleta')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.divisao')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.grupo')),
            ],
        ),
    ]
