# Generated by Django 4.2.14 on 2024-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='tipo_divisao',
            field=models.CharField(choices=[('G', 'Grupo'), ('I', 'Individual')], default='', max_length=1),
        ),
    ]
