# Generated by Django 4.2.14 on 2024-09-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterField(
            model_name='divisao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.modalidade'),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='tipo_divisao',
            field=models.CharField(choices=[('I', 'Individual'), ('G', 'Grupo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Masc.', 'Masculino'), ('Geral', 'Geral'), ('Fem.', 'Feminino')], default='', max_length=5),
        ),
    ]
