# Generated by Django 4.2.14 on 2024-11-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='representante_esportivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_siad.representanteesportivo'),
        ),
    ]
