# Generated by Django 4.2.14 on 2024-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0002_alter_noticia_options_alter_divisao_modalidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalidade',
            old_name='evento_original',
            new_name='edicao_evento',
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Geral', 'Geral'), ('Masc.', 'Masculino'), ('Fem.', 'Feminino')], default='', max_length=5),
        ),
    ]
