# Generated by Django 4.2.14 on 2024-11-07 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0003_atletagrupodivisao_representante_esportivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletagrupodivisao',
            name='divisao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_siad.divisao'),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='tipo_divisao',
            field=models.CharField(choices=[('I', 'Individual'), ('G', 'Grupo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Masc.', 'Masculino'), ('Geral', 'Geral'), ('Fem.', 'Feminino')], default='', max_length=5),
        ),
    ]
