# Generated by Django 4.2.14 on 2024-09-14 21:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0003_rename_evento_original_modalidade_edicao_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='tipo_divisao',
            field=models.CharField(choices=[('G', 'Grupo'), ('I', 'Individual')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Fem.', 'Feminino'), ('Geral', 'Geral'), ('Masc.', 'Masculino')], default='', max_length=5),
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='eventos/<function Edital.<lambda> at 0x000001F8F6C0B880>/%Y/%m/%d_%s')),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editais', to='app_siad.edicaoevento')),
            ],
        ),
    ]
