# Generated by Django 4.2.14 on 2024-09-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0004_alter_divisao_tipo_divisao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='data_postagem',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='edital',
            name='arquivo',
            field=models.FileField(upload_to='eventos/%Y/%m/%d/%s'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siad.edicaoevento'),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Fem.', 'Feminino'), ('Masc.', 'Masculino'), ('Geral', 'Geral')], default='', max_length=5),
        ),
    ]
