# Generated by Django 4.2.14 on 2024-09-14 21:55

import app_siad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0005_remove_edital_data_postagem_remove_edital_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisao',
            name='tipo_divisao',
            field=models.CharField(choices=[('I', 'Individual'), ('G', 'Grupo')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='edital',
            name='arquivo',
            field=models.FileField(upload_to=app_siad.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Geral', 'Geral'), ('Masc.', 'Masculino'), ('Fem.', 'Feminino')], default='', max_length=5),
        ),
    ]
