# Generated by Django 4.2.14 on 2024-09-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siad', '0006_alter_divisao_tipo_divisao_alter_edital_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='categoria',
            field=models.CharField(choices=[('Masc.', 'Masculino'), ('Fem.', 'Feminino'), ('Geral', 'Geral')], default='', max_length=5),
        ),
    ]
